### ISSUE TITLE
ansible-doc error

### ISSUE THREAD

**Issue by chicuongha** [TerryHowe/ansible-modules-hashivault#241]
Hello

I'm using virtualenv and got error with ansible-doc hashivault_*
However ansible-doc -l | grep hashivault sucess list all hashivault modules
```
$ ansible-doc hashivault_write
ERROR! module hashivault_write missing documentation (or could not parse documentation): unknown doc_fragment(s) in file /home/cloud-user/.virtualenvs/py3_ansible/lib/python3.8/site-packages/ansible/modules/hashivault/hashivault_write.py: hashivault

# pip list
Package                    Version
-------------------------- ----------
ansible                    2.9.7
ansible-lint               4.2.0
ansible-modules-hashivault 4.5.0
certifi                    2020.4.5.1
cffi                       1.14.0
chardet                    3.0.4
cryptography               2.9.2
hvac                       0.10.1
idna                       2.9
Jinja2                     2.11.2
jmespath                   0.9.5
MarkupSafe                 1.1.1
pip                        20.1
pycparser                  2.20
PyYAML                     5.3.1
requests                   2.23.0
ruamel.yaml                0.16.10
ruamel.yaml.clib           0.2.0
setuptools                 46.1.3
six                        1.14.0
urllib3                    1.25.9
wheel                      0.34.2
```

**Comment by TerryHowe** [comment]
I'm struggling to reproduce this problem. I created a fresh venv and installed 4.5.0:
```
$ pip list
Package                    Version
-------------------------- ----------
ansible                    2.9.7
ansible-modules-hashivault 4.5.0
certifi                    2020.4.5.1
cffi                       1.14.0
chardet                    3.0.4
cryptography               2.9.2
hvac                       0.10.1
idna                       2.9
Jinja2                     2.11.2
MarkupSafe                 1.1.1
pip                        20.1
pycparser                  2.20
PyYAML                     5.3.1
requests                   2.23.0
setuptools                 46.1.3
six                        1.14.0
urllib3                    1.25.9
wheel                      0.34.2
```

**Comment by TerryHowe** [comment]
I would assume `ruamel.yaml` is stepping on something in the regular yaml.

**Comment by chicuongha** [comment]
I created a new virtualenv and just install ansible and same error
```
$ pip list
Package                    Version
-------------------------- ----------
ansible                    2.9.7
ansible-modules-hashivault 4.5.0
certifi                    2020.4.5.1
cffi                       1.14.0
chardet                    3.0.4
cryptography               2.9.2
hvac                       0.10.1
idna                       2.9
Jinja2                     2.11.2
MarkupSafe                 1.1.1
pip                        20.1
pycparser                  2.20
PyYAML                     5.3.1
requests                   2.23.0
setuptools                 46.1.3
six                        1.14.0
urllib3                    1.25.9
wheel                      0.34.2
$ ansible-doc hashivault_write
ERROR! module hashivault_write missing documentation (or could not parse documentation): unknown doc_fragment(s) in file /home/chiku/.virtualenvs/test/lib/python3.8/site-packages/ansible/modules/hashivault/hashivault_write.py: hashivault
$ ansible-doc -vvv hashivault_write
ansible-doc 2.9.7
  config file = None
  configured module search path = ['/home/chiku/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/chiku/.virtualenvs/test/lib/python3.8/site-packages/ansible
  executable location = /home/chiku/.virtualenvs/test/bin/ansible-doc
  python version = 3.8.2 (default, Apr  8 2020, 14:31:25) [GCC 9.3.0]
No config file found; using defaults
Traceback (most recent call last):
  File "/home/chiku/.virtualenvs/test/lib/python3.8/site-packages/ansible/cli/doc.py", line 195, in run
    doc, plainexamples, returndocs, metadata = DocCLI._get_plugin_doc(plugin, loader, search_paths)
  File "/home/chiku/.virtualenvs/test/lib/python3.8/site-packages/ansible/cli/doc.py", line 302, in _get_plugin_doc
    doc, plainexamples, returndocs, metadata = get_docstring(filename, fragment_loader, verbose=(context.CLIARGS['verbosity'] > 0))
  File "/home/chiku/.virtualenvs/test/lib/python3.8/site-packages/ansible/utils/plugin_docs.py", line 128, in get_docstring
    add_fragments(data['doc'], filename, fragment_loader=fragment_loader)
  File "/home/chiku/.virtualenvs/test/lib/python3.8/site-packages/ansible/utils/plugin_docs.py", line 116, in add_fragments
    raise AnsibleError('unknown doc_fragment(s) in file {0}: {1}'.format(filename, to_native(', '.join(unknown_fragments))))
ansible.errors.AnsibleError: unknown doc_fragment(s) in file /home/chiku/.virtualenvs/test/lib/python3.8/site-packages/ansible/modules/hashivault/hashivault_write.py: hashivault
ERROR! module hashivault_write missing documentation (or could not parse documentation): unknown doc_fragment(s) in file /home/chiku/.virtualenvs/test/lib/python3.8/site-packages/ansible/modules/hashivault/hashivault_write.py: hashivault

```

**Comment by TerryHowe** [comment]
I assume the problem is related to `No config file found; using defaults`

**Comment by chicuongha** [comment]
Most of time ansible works well without ansible.cfg
I keep all defaults.
I did touch ansible.cfg so no anymore this No config file found, but still failed.
ansible-doc uri works fine

**Comment by TerryHowe** [comment]
What OS are you running on anyway?

**Comment by chicuongha** [comment]
I use Archlinux.

**Comment by TerryHowe** [comment]
I'm on Ubuntu at the moment, I was expecting you to say osx

**Comment by TerryHowe** [comment]
You don't happen to have a `~/.ansible/plugins/` directory do you? I had one and my doc fragments were pulling out of there instead of what is installed. I haven't figured out how that is created.

**Comment by chicuongha** [comment]
I don't have ~/.ansible/plugins
just ~/.ansible/tmp/ ~/.ansible/collections/ ~/.ansible/cp/

**Comment by TerryHowe** [comment]
I'm at a loss on how to recreate this.

**Comment by TerryHowe** [comment]
Please reopen if you can get me a better description of how to recreate this problem. I'm at a loss.
