### ISSUE TITLE
Permission denied when creating a policy

### ISSUE THREAD

**Issue by mleneveut** [TerryHowe/ansible-modules-hashivault#475]
Hi,

I try to create a policy with this code : 

```
- hashivault_policy:
    name: 'my-policy'
    rules_file: 'rules.hcl'
    state: 'present'
```

I got this error : 

```
The full traceback is:
Traceback (most recent call last):
  File "/home/mleneveut/.ansible/tmp/ansible-tmp-1718114853.9752536-18069-263374009772086/AnsiballZ_hashivault_policy.py", line 107, in <module>
    _ansiballz_main()
  File "/home/mleneveut/.ansible/tmp/ansible-tmp-1718114853.9752536-18069-263374009772086/AnsiballZ_hashivault_policy.py", line 99, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/mleneveut/.ansible/tmp/ansible-tmp-1718114853.9752536-18069-263374009772086/AnsiballZ_hashivault_policy.py", line 47, in invoke_module
    runpy.run_module(mod_name='ansible.modules.hashivault_policy', init_globals=dict(_module_fqn='ansible.modules.hashivault_policy', _modlib_path=modlib_path),
  File "<frozen runpy>", line 226, in run_module
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/tmp/ansible_hashivault_policy_payload_y6ia5nfd/ansible_hashivault_policy_payload.zip/ansible/modules/hashivault_policy.py", line 117, in <module>
  File "/tmp/ansible_hashivault_policy_payload_y6ia5nfd/ansible_hashivault_policy_payload.zip/ansible/modules/hashivault_policy.py", line 52, in main
  File "/tmp/ansible_hashivault_policy_payload_y6ia5nfd/ansible_hashivault_policy_payload.zip/ansible/module_utils/hashivault.py", line 154, in wrapper
  File "/tmp/ansible_hashivault_policy_payload_y6ia5nfd/ansible_hashivault_policy_payload.zip/ansible/modules/hashivault_policy.py", line 71, in hashivault_policy
  File "/usr/lib/python3/dist-packages/hvac/api/system_backend/policy.py", line 18, in list_policies
    return self._adapter.get(
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/hvac/adapters.py", line 113, in get
    return self.request("get", url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/hvac/adapters.py", line 364, in request
    response = super(JSONAdapter, self).request(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/hvac/adapters.py", line 330, in request
    utils.raise_for_error(
  File "/usr/lib/python3/dist-packages/hvac/utils.py", line 41, in raise_for_error
    raise exceptions.Forbidden(message, errors=errors, method=method, url=url)
hvac.exceptions.Forbidden: 1 error occurred:
        * permission denied

, on get https://_redacted_/v1/sys/policy
fatal: [localhost]: FAILED! => {
    "changed": false,
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/mleneveut/.ansible/tmp/ansible-tmp-1718114853.9752536-18069-263374009772086/AnsiballZ_hashivault_policy.py\", line 107, 
in <module>\n    _ansiballz_main()\n  File \"/home/mleneveut/.ansible/tmp/ansible-tmp-1718114853.9752536-18069-263374009772086/AnsiballZ_hashivault_policy.py\", line 99, in _ansiballz_main\n   
 invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/mleneveut/.ansible/tmp/ansible-tmp-1718114853.9752536-18069-263374009772086/AnsiballZ_hashivault_policy.py\", line 47, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.hashivault_policy', init_globals=dict(_module_fqn='ansible.modules.hashivault_policy', _modlib_path=modlib_path),\n  File \"<frozen runpy>\", line 226, in run_module\n  File \"<frozen runpy>\", line 98, in _run_module_code\n  File \"<frozen runpy>\", line 88, in _run_code\n  File \"/tmp/ansible_hashivault_policy_payload_y6ia5nfd/ansible_hashivault_policy_payload.zip/ansible/modules/hashivault_policy.py\", line 117, in <module>\n  File \"/tmp/ansible_hashivault_policy_payload_y6ia5nfd/ansible_hashivault_policy_payload.zip/ansible/modules/hashivault_policy.py\", line 52, in main\n  File \"/tmp/ansible_hashivault_policy_payload_y6ia5nfd/ansible_hashivault_policy_payload.zip/ansible/module_utils/hashivault.py\", line 154, in wrapper\n  File \"/tmp/ansible_hashivault_policy_payload_y6ia5nfd/ansible_hashivault_policy_payload.zip/ansible/modules/hashivault_policy.py\", line 71, in hashivault_policy\n  File \"/usr/lib/python3/dist-packages/hvac/api/system_backend/policy.py\", line 18, in list_policies\n    return self._adapter.get(\n           ^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/hvac/adapters.py\", line 113, in get\n    return self.request(\"get\", url, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/hvac/adapters.py\", line 364, in request\n    response = super(JSONAdapter, self).request(*args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3/dist-packages/hvac/adapters.py\", line 330, in request\n    utils.raise_for_error(\n  File \"/usr/lib/python3/dist-packages/hvac/utils.py\", line 41, in raise_for_error\n    raise exceptions.Forbidden(message, errors=errors, method=method, url=url)\nhvac.exceptions.Forbidden: 1 error occurred:\n\t* permission denied\n\n, on get https://_redacted_/v1/sys/policy\n",
    "module_stdout": "",
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
    "rc": 1
}
```

I'm using : 

- ansible 9.2.0
- ansible core 2.16.3
- hvac 0.11.2
- python 3.12.3
- Ubuntu 24.04

I installed the module with : `ansible-galaxy install 'git+https://github.com/TerryHowe/ansible-modules-hashivault.git'`

I'm using an administrator token : 

```
export VAULT_ADDR="https://_redacted_"
export VAULT_AUTHTYPE="token"
export VAULT_TOKEN="hvs._redacted_"

VAULT_TOKEN="hvs._redacted_" vault token lookup
Key                 Value
---                 -----
accessor            _redacted_
creation_time       1716305488
creation_ttl        768h
display_name        ldap-mleneveut
entity_id           e54dfc6b-xxxx-xxxx-xxxx-e25b8cc91927
expire_time         2024-06-22T17:31:28.97883878+02:00
explicit_max_ttl    0s
id                  hvs._redacted_
issue_time          2024-05-21T17:31:28.978842999+02:00
meta                map[username:mleneveut]
num_uses            0
orphan              true
path                auth/ldap/login/mleneveut
policies            [administrators default]
renewable           true
ttl                 265h26m42s
type                service
```

With these creds I can list policies with the Vault CLI `vault policy list`

or with the Vault API : 

```
curl -X LIST --header "X-Vault-Token:hvs._redacted_" https://_redacted_/v1/sys/policies/acl

{"request_id":"e6fd3626-c4dd-4767-90a5-79548e7a9cc4","lease_id":"","renewable":false,"lease_duration":0,"data":{"keys":[...]}}
```

I successfully used the module to read and create secrets witht he same token.

Do you have an idea of the problem or what I could try to debug this ?

Thanks.

**Comment by mleneveut** [comment]
Seems I get the same permission denied errors for the requests GET /v1/sys/policy and /v1/sys/policy/{name} so it seems a problem on my end, sorry.

**Comment by mleneveut** [comment]
Yes sorry, this user doesn't have the permissions for /v1/sys/policy.

What I was trying to do is to create /v1/sys/policy/acl, which is not supported by this module. So I made you a PR to add the ACL policies suppport
